### ISSUE TITLE
Minute Rounding

### ISSUE THREAD

**Issue by Thawus** [AndroX55/Mq-Islamic-Local-Prayer-Times#1]
Shalat time rounding should be using CEIL instead of INT because it is about start time. for example, by calculation it is known 12:05:04 --> if using round, it may become 12:05 (rounded down) but 12:05 is not started yet. so the idea to round should always round-up. 12:06 is better "sudah masuk waktu".
Except for Syuruq time, Dr. A Rinto algoritm is introduce the syuruq as the end-of-shubuh time. So it should use FLOOR, safety for Shubuh. 

by the way, there is already ikhtiyat (safety coefficient), but for better idea, suggested to use above rounding term.

**Comment by AndroX55** [comment]
gotcha bro, thanks for the correction. but i'm not including syuruq sensor for now.
fixed..
